SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS term;
DROP TABLE IF EXISTS `academic_year`;
DROP TABLE IF EXISTS subject;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS classroom;
DROP TABLE IF EXISTS grade;
DROP TABLE IF EXISTS role;

SET FOREIGN_KEY_CHECKS = 1;


